# Generated by Django 3.2.6 on 2021-09-07 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0012_auto_20210907_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyec',
            name='equipo',
        ),
        migrations.AddField(
            model_name='proyec',
            name='equipo',
            field=models.ManyToManyField(related_name='equipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
