# Generated by Django 3.2.6 on 2021-09-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_auto_20210907_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolproyectousuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='rolproyectousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='RolProyecto',
        ),
        migrations.DeleteModel(
            name='RolProyectoUsuario',
        ),
    ]
