# Generated by Django 3.2.6 on 2021-09-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_rolproyecto_rolproyectousuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolProyectoUsuario',
        ),
    ]
