# Generated by Django 3.2.6 on 2021-09-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_alter_rolproyecto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolproyecto',
            old_name='proyecto',
            new_name='id_proyecto',
        ),
        migrations.RenameField(
            model_name='rolproyecto',
            old_name='rol',
            new_name='id_rol',
        ),
    ]
