# Generated by Django 3.2.6 on 2021-09-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_auto_20210915_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='fecha_cancelado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='fecha_concluido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='fecha_cancelado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='fecha_concluido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
