# Generated by Django 3.2.6 on 2021-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0024_auto_20210916_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiausuario',
            old_name='fecha_cancelado',
            new_name='fecha_Doing',
        ),
        migrations.RenameField(
            model_name='historiausuario',
            old_name='fecha_concluido',
            new_name='fecha_Done',
        ),
        migrations.RenameField(
            model_name='historiausuario',
            old_name='fecha_inicio',
            new_name='fecha_QA',
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='aprobado_PB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='fecha_ToDo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Iniciado', 'Iniciado'), ('Concluido', 'Concluido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15),
        ),
    ]
