# Generated by Django 3.2.6 on 2021-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0025_auto_20210916_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='estimacion_scrum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='estimacion_user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
