# Generated by Django 3.2.6 on 2021-09-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0027_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='asignacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
