# Generated by Django 3.2.6 on 2021-09-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0028_alter_historiausuario_asignacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiausuario',
            options={'verbose_name': 'Historia de Usuario', 'verbose_name_plural': 'Historias de Usuario'},
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='prioridad_numerica',
            field=models.IntegerField(default=1),
        ),
    ]
