# Generated by Django 3.2.6 on 2021-09-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0029_auto_20210922_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
