# Generated by Django 3.2.6 on 2021-09-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_historiausuario_sprint_backlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaUsuario',
        ),
    ]
