# Generated by Django 3.2.6 on 2021-09-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_delete_rolproyectousuario'),
        ('user', '0003_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ManyToManyField(related_name='user_rol_proyecto', to='proyectos.RolProyecto'),
        ),
    ]
