# Generated by Django 3.2.6 on 2021-08-30 05:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyec',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyec',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='proyec',
            name='equipo',
        ),
        migrations.AddField(
            model_name='proyec',
            name='equipo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='fecha_de_creacion'),
        ),
    ]
