# Generated by Django 3.2.6 on 2021-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyec_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyec',
            name='estado',
            field=models.CharField(choices=[(1, 'PENDIENTE'), (2, 'Iniciado'), (3, 'Concluido'), (4, 'Cancelado')], default='lala', max_length=15),
        ),
    ]
