# Generated by Django 3.2.6 on 2021-08-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyec_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyec',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Iniciado'), (3, 'Concluido'), (4, 'Cancelado')], default=1, max_length=15),
        ),
    ]
