# Generated by Django 3.2.6 on 2021-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyec_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyec',
            name='fecha',
        ),
        migrations.AddField(
            model_name='proyec',
            name='fecha_ultima_modificacion',
            field=models.DateField(auto_now=True, verbose_name='fecha_modificacion'),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('I', 'Iniciado'), ('T', 'Concluido'), ('C', 'Cancelado')], default=1, max_length=15),
        ),
    ]
