# Generated by Django 3.2.6 on 2021-08-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20210830_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyec',
            name='fecha_ultima_modificacion',
        ),
        migrations.AddField(
            model_name='proyec',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='proyec',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Iniciado', 'Iniciado'), ('Concluido', 'Concluido'), ('Cancelado', 'Cancelado')], default=1, max_length=15),
        ),
    ]
