# Generated by Django 3.2.6 on 2021-09-03 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0008_auto_20210830_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyec',
            name='equipo',
            field=models.ManyToManyField(related_name='equipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
