# Generated by Django 3.2.6 on 2021-09-08 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_delete_rolproyectousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolproyecto',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
