# Generated by Django 3.2.6 on 2021-09-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_rolproyecto_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={'verbose_name': 'nombre', 'verbose_name_plural': 'nombres'},
        ),
    ]
