# Generated by Django 3.2.6 on 2021-09-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_auto_20210908_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={'verbose_name': 'RolProyecto', 'verbose_name_plural': 'RolesProyectos'},
        ),
        migrations.RenameField(
            model_name='rolproyecto',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='rolproyecto',
            old_name='id_rol',
            new_name='rol',
        ),
    ]
