# Generated by Django 3.2.6 on 2021-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapermitidos',
            name='correo',
            field=models.TextField(unique=True),
        ),
    ]
