# Generated by Django 3.2.6 on 2021-09-29 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0032_delete_historiausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=15)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_s', to='proyectos.proyec')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
            },
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('ToDo', 'ToDo'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA')], default=1, max_length=15)),
                ('fecha', models.DateField(auto_now=True, verbose_name='fecha')),
                ('estimacion', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='fecha cre')),
                ('fecha_ToDo', models.DateField(blank=True, null=True)),
                ('fecha_Doing', models.DateField(blank=True, null=True)),
                ('fecha_Done', models.DateField(blank=True, null=True)),
                ('fecha_QA', models.DateField(blank=True, null=True)),
                ('estado_anterior', models.CharField(default='Pendiente', max_length=200)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default=1, max_length=15)),
                ('prioridad_numerica', models.IntegerField(default=1)),
                ('aprobado_PB', models.BooleanField(default=False)),
                ('sprint_backlog', models.BooleanField(default=False)),
                ('estimacion_user', models.PositiveIntegerField(default=0)),
                ('estimacion_scrum', models.PositiveIntegerField(default=0)),
                ('asignacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyectos.proyec')),
                ('sprint', models.ForeignKey(blank=True, limit_choices_to={'estado': 'Pendiente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='sprint.sprint')),
            ],
            options={
                'verbose_name': 'Historia de Usuario',
                'verbose_name_plural': 'Historias de Usuario',
            },
        ),
    ]
