# Generated by Django 3.2.6 on 2021-09-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_delete_sprint'),
        ('sprint', '0002_sprint_hu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_s', to='proyectos.proyec'),
        ),
    ]
