# Generated by Django 3.2.6 on 2021-10-10 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0002_sprint_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadDiariaEnSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_diaria_horas', models.PositiveIntegerField(default=8)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='el_sprint', to='sprint.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='el_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
