# Generated by Django 3.2.6 on 2021-09-27 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_historiausuario_sprint_backlog'),
        ('sprint', '0003_alter_sprint_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='hu',
            field=models.ForeignKey(blank=True, limit_choices_to={'aprobado_PB': True, 'sprint_backlog': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='proyectos.historiausuario'),
        ),
    ]
