# Generated by Django 3.2.6 on 2021-10-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_historiausuario_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiausuario',
            old_name='Product_Owner',
            new_name='product_owner',
        ),
    ]
