# Generated by Django 3.2.6 on 2021-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0005_rename_product_owner_historiausuario_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('ToDo', 'ToDo'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA')], default='Pendiente', max_length=15),
        ),
    ]
