# Generated by Django 3.2.6 on 2021-09-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_historiausuario_sprint_backlog'),
        ('sprint', '0005_auto_20210927_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='hu',
            field=models.ManyToManyField(blank=True, limit_choices_to={'aprobado_PB': True, 'proyecto': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_s', to='proyectos.proyec'), 'sprint_backlog': False}, null=True, related_name='hu', to='proyectos.HistoriaUsuario'),
        ),
    ]
