# Generated by Django 3.2.6 on 2021-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_alter_historiausuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacidad_de_equipo_sprint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprint',
            name='capacidad_equipo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
