# Generated by Django 3.2.6 on 2021-10-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_alter_historiausuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha de creacion'),
        ),
    ]
