# Generated by Django 3.2.6 on 2021-10-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0007_sprint_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='fecha_prueba',
            field=models.TextField(blank=True, null=True),
        ),
    ]
