# Generated by Django 3.2.6 on 2021-10-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0007_auto_20211018_2124'),
        ('sprint', '0007_historiausuario_rechazado_pb'),
    ]

    operations = [
    ]
