# Generated by Django 3.2.6 on 2021-10-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0008_historiausuario_fecha_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiausuario',
            name='fecha_prueba',
        ),
        migrations.CreateModel(
            name='Historial_HU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='fecha cre')),
                ('descripcion', models.TextField()),
                ('hu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_hu', to='sprint.historiausuario')),
            ],
        ),
    ]
