# Generated by Django 3.2.6 on 2021-10-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0008_merge_20211022_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('hora_trabajo', models.PositiveIntegerField(default=0)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='actividades',
            field=models.ManyToManyField(related_name='actividades', to='sprint.Actividad'),
        ),
    ]
