# Generated by Django 3.2.6 on 2021-10-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0009_auto_20211019_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_hu',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial_hu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
