# Generated by Django 3.2.6 on 2021-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0009_auto_20211024_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='id_sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
