# Generated by Django 3.2.6 on 2021-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0010_actividad_id_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
