# Generated by Django 3.2.6 on 2021-10-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0008_merge_20211022_1052'),
        ('sprint', '0010_auto_20211019_2155'),
    ]

    operations = [
    ]
