# Generated by Django 3.2.6 on 2021-10-25 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0011_merge_20211022_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='QA_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Estado_HU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
                ('hu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_hu', to='sprint.historiausuario')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_sprint', to='sprint.sprint')),
            ],
        ),
    ]
