# Generated by Django 3.2.6 on 2021-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0012_auto_20211025_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_hu',
            name='PP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estado_hu',
            name='desarrollador',
            field=models.TextField(default='User'),
        ),
        migrations.AddField(
            model_name='estado_hu',
            name='prioridad',
            field=models.TextField(default='Baja'),
        ),
    ]
