# Generated by Django 3.2.6 on 2021-10-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0011_actividad_fecha'),
        ('sprint', '0013_auto_20211025_0120'),
    ]

    operations = [
    ]
