# Generated by Django 3.2.6 on 2021-10-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0014_merge_0011_actividad_fecha_0013_auto_20211025_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='sprint.Actividad'),
        ),
    ]
