# Generated by Django 3.2.6 on 2021-10-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0017_auto_20211028_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
