# Generated by Django 3.2.6 on 2021-10-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0018_historiausuario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_hu',
            name='aprobado_QA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estado_hu',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='estado_hu',
            name='rechazado_QA',
            field=models.BooleanField(default=False),
        ),
    ]
