# Generated by Django 3.2.6 on 2021-10-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0015_alter_historiausuario_actividades'),
        ('sprint', '0015_auto_20211027_0200'),
        ('sprint', '0019_auto_20211028_2210'),
    ]

    operations = [
    ]
