# Generated by Django 3.2.6 on 2021-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0020_merge_20211029_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('ToDo', 'ToDo'), ('Doing', 'Doing'), ('Done', 'Done'), ('QA', 'QA'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15),
        ),
    ]
