# Generated by Django 3.2.6 on 2021-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0020_merge_20211029_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='horas_restantes',
            field=models.IntegerField(default=0),
        ),
    ]
