# Generated by Django 3.2.6 on 2021-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0021_historiausuario_horas_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='horas_trabajadas',
            field=models.IntegerField(default=0),
        ),
    ]
