# Generated by Django 3.2.6 on 2021-11-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0021_auto_20211111_1519'),
        ('sprint', '0023_historiausuario_horas_trabajadas_en_total'),
    ]

    operations = [
    ]
