# Generated by Django 3.2.6 on 2021-11-17 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0024_merge_20211116_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='asignacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='product_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PO', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='sprint',
            field=models.ForeignKey(blank=True, limit_choices_to={'estado': 'Pendiente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint', to='sprint.sprint'),
        ),
    ]
