# Generated by Django 3.2.6 on 2021-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0025_auto_20211117_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='suma_planing_poker',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
