# Generated by Django 3.2.6 on 2021-11-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0025_auto_20211117_0929'),
        ('sprint', '0026_sprint_suma_planing_poker'),
    ]

    operations = [
    ]
